[package]
name = "iron_proxy"
version.workspace = true
edition.workspace = true

[dependencies]
observability = { path = "../observability" }
config = { path = "../config" }
health = { path = "../health" }
proxy_l4 = { path = "../proxy_l4" }
proxy_l7 = { path = "../proxy_l7" }
admin = { path = "../admin" }
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
reqwest.workspace = true
serde_json.workspace = true
