[package]
name = "proxy_l7"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
config = { path = "../config" }
tokio.workspace = true
tracing.workspace = true
hyper.workspace = true
hyper-util.workspace = true
http-body-util.workspace = true
bytes.workspace = true
